### ISSUE TITLE
Self registration with invite code?

### ISSUE THREAD

**Issue by poVoq** [nitnelave/lldap#287]
Would it be possible to have the option in the webinterface to allow users to register themselves with an invite code?

Invite codes could be permanent or time/number-limited?

Maybe users could even be allowed to generate their own invite codes?

**Comment by poVoq** [comment]
While this would be still nice to have in LLDAP, there is this relatively simple php app that can provide this functionality:

https://github.com/matheusfillipe/ldap-signup

the `special-auth` branch is slightly modified to work with invite-codes.

I will probably test it more in the coming days and provide a working configuration for the LLDAP documentation.

Somewhat related is the awesome Canaille app: https://gitlab.com/yaal/canaille which allows managing LDAP users and groups with invites and also has an additional Oauth2 endpoint (similar to Keycloak, but much less complex). It also does not support self-registration yet, but can be a great companion to LLDAP never the less I think (I need to actually test it with LLDAP).

**Comment by pixelrazor** [comment]
Looking at maybe taking this up after the yew upgrade.

I'm imagining that we can use tokens nearly identically to password reset (if not using the same model/table) where that token is deleted when used and we generate a short lived cookie for that one endpoint (a new endpoint created for this).

This leaves the UI changes. It should only be visible to admin since that's the only group with write privilege. This could potentially be a new menu item in the navbar along 'users' and 'groups'? From there, it could be either or both of:

1. Just a button to generate a sharable link. big critical test indicating that you shouldn't open it or it will invalidate it for the user you send it to
2. A field where you type and email and have a button to send an email to that address containing the new link

2 feels a bit redundant to me - while we COULD prefill the email in the creation form, i think it should be kept open for users to use a different email than the one it was sent to. 

I feel like there COULD be an argument for wanting the ability to make a link that also adds the new user to certain groups, but i don't think that's really the best idea, and the admin can easily add them after creation.

Then of course we'll need a new endpoint for the creation page. This could be pretty much the same as the current user creation page - there could ideally be a way we share that part of the frontend with some refactoring of that component

**Comment by nitnelave** [comment]
Oh, and regarding adding the user to certain groups, that could be added later on by making that a property of the invitation: in the invitation list screen, the admin would have a way to add groups to the invitation, that will then be added to the user on account creation.

**Comment by pixelrazor** [comment]
> We could also think about email confirmation?

Would this end up being specific to this path, or should that also become part of the process when an admin creates a user?

re: adding to groups - i still think it'd be bbetter to have the admin control groups manually AFTER account creation instead of having  it attached to the creation link. That being said i can't seem to form a solid argument so i'll sway to whatever way you prefer.

SSome of these requirements are enough to warrant a different model for these tokens since we've deviated a bit from the password reset tokens. I'll have to do enough investigating to ensure it can be done without (hopefully) breaking previouus versions.. IIRC isn't there some breaking db migration planned at SOME point in time TBD?

**Comment by nitnelave** [comment]
We'll have to be careful and use transactions when checking for the token's validity, removing it and creating the user at the same time.

**Comment by nitnelave** [comment]
I was thinking back on this feature, and compared to creating the account directly for the user, the only thing that changes is that the user is able to pick their username. That doesn't seem worth the extra complexity.

**Comment by poVoq** [comment]
Its a completely different use-case. If you want to run a semi-public service you can't manually create accounts all the time. But anyway... there are way to achieve this without having it built-into LLDAP directly, so not a big deal.

**Comment by pixelrazor** [comment]
You'll be manually creating links and sending them out anyways, and have to deal with the security implications depending on how you distribute them.

**Comment by poVoq** [comment]
In my original feature request I was rather thinking about shared (time/number limited) invite codes, so that would not require manual intervention except for making these shared invite codes from time to time.
