### ISSUE TITLE
Remove Hardcoded Volume

### ISSUE THREAD

**Issue by RedlineTriad** [nitnelave/lldap#393]
The LLDAP docker images include hardcoded volume paths.
Which means that if you don't want to mount all of `/data` then it will create an anonymous volume which is very annoying when deploying.

In general I don't think `VOLUME` should be used in Dockerfiles, since there is no way to change it afterwards.
In my case I want `lldap_config.toml` to be mounted read only to the local file system, and then use `/data/dynamic` for storing the database.
`docker-compose.yml`
```yml
    volumes:
      - lldap_data:/data/dynamic
      - ./lldap_config.toml:/data/lldap_config.toml:ro
```

I can work around this by using a different directory for the database or config file, but it's still a bit cumbersome.

**Comment by nitnelave** [comment]
I'm not sure I understand all of your concerns.
What prevents you from mounting all of /data, but then on top of it mount
the config readonly?

The dockerfile is primarily made for ease of use. For a new user, using the
image is the easiest. If you're an advanced user with a non standard use
case, that's also supported: we provide the dockerfile, you can either
modify it and build your own image, or build in top of it.

I'd rather not modify the standard image since it would require people to
migrate their docker compose configuration.

**Comment by RedlineTriad** [comment]
If you create a volume in `Dockerfile` there *has* to be a volume there no matter what.
If you don't mount it, it creates an anonymous volume, there is no way to disable or block this.
Even if you only want to mount a sub-path, or not entirely, for a temporary test instance, it will still create it.

If you don't think any of this is important it's fine if you close this issue since I have my own workaround now.

**Comment by nitnelave** [comment]
I think for most people it's fine to have an (almost empty) volume, even if it's not used. Those who know better can make their own Dockerfile and image.
