### ISSUE TITLE
 Could not get admin user, trying to create it: Entity not found: `admin`

### ISSUE THREAD

**Issue by moses-keqi** [nitnelave/lldap#465]
Could not get admin user, trying to create it: Entity not found: `admin`

<img width="944" alt="image" src="https://user-images.githubusercontent.com/7346210/222654790-b598378e-1ca6-45d1-b684-d1b7058123fd.png">

**Comment by martadinata666** [comment]
the log is pretty clear `minimum password 8 char, found 3`

**Comment by moses-keqi** [comment]
好的 感谢

**Comment by nitnelave** [comment]
I really have to make those warnings clearer. On first startup they are expected.

In your case, as @martadinata666 pointed out, the problem is that the server crashed because the admin password was too short. Even 8 characters is pretty short, to be honest. But the best is to change it after setup, so it's not written down anywhere.

**Comment by moses-keqi** [comment]
Thank you
