### ISSUE TITLE
Create a CLI tool to change password

### ISSUE THREAD

**Issue by behrooz** [nitnelave/lldap#473]
I cant find any sample how to create a user and change password with graphql 
could you please help me to write one 
I am working with python graphql and i want to request to lldap change password graphql 
thanks

**Comment by nitnelave** [comment]
Currently there's no way to change the password of a user via GraphQL, and I don't plan on adding one:

 - the easiest is to create the user and let them set the password themselves through password reset (via the web interface)
 - otherwise you can set the password through LDAP (or with e.g. keycloak going through LDAP)

The reasoning for that is that:
 - I don't provide a HTTPS interface bit instead count on the admin to wrap the API behind a proxy with HTTPS.
 - as such, by default, I don't trust the HTTP interface and I don't want clear text passwords in there.
 - setting the passwords via OPAQUE (what the web UI does) works even over plain HTTP because it's a zero knowledge protocol that doesn't reveal any info about the password.
 - LDAP is supposed to be only open to the internal network (or just the other docker containers) rather than the entire internet, so it's considered safer (and you have LDAPS as well)

What I could do is provide a client binary that sets a user's password through OPAQUE from the command line: you give it the server url, the admin credentials, and the user credentials you want to set, and it does the safe password negotiation with the server. Would that work for you?

**Comment by nitnelave** [comment]
As I mentioned, one option is to have a separate binary that'll do the OPAQUE negotiation for you. You can already create a user with GraphQL, without password. The flow (from python) would then look like:

 - Using the GraphQL API, create the user
 - Then call a simple binary with parameters to set the password of that user (using e.g. `subprocess.run(['lldap_set_password', '--jwt_token', token, '--user', user, '--password', password, '--url', server_url])`).

Would that work for you?

**Comment by behrooz** [comment]
That is good but id dont understand simple binary
what is subprocess ? how to install and run it ?

**Comment by nitnelave** [comment]
You mentioned you're using python, right? `subprocess` is part of the standard library (https://docs.python.org/3/library/subprocess.html), and it's the most common way of calling external binaries (external programs). For instance, if you want to call `ls -l` like you would do from the shell, you can do `subprocess.run(["ls", "-l"])` in your python code. This will call from your python code the _external program_ `ls` with the option `-l`.

Similarly, _if we had a program called `lldap_set_password`_, you could write what I wrote above to call and run it, like you would be able to do from your shell (from the shell you'd write `lldap_set_password --jwt_token abcdef --user tom --password superPa55w0rd --url lldap.my_server.com`).

This program _doesn't exist yet_ (`lldap_set_password`), but I'm proposing to create it as a way to solve this problem.

**Comment by behrooz** [comment]
> You mentioned you're using python, right? `subprocess` is part of the standard library (https://docs.python.org/3/library/subprocess.html), and it's the most common way of calling external binaries (external programs). For instance, if you want to call `ls -l` like you would do from the shell, you can do `subprocess.run(["ls", "-l"])` in your python code. This will call from your python code the _external program_ `ls` with the option `-l`.
> 
> Similarly, _if we had a program called `lldap_set_password`_, you could write what I wrote above to call and run it, like you would be able to do from your shell (from the shell you'd write `lldap_set_password --jwt_token abcdef --user tom --password superPa55w0rd --url lldap.my_server.com`).
> 
> This program _doesn't exist yet_ (`lldap_set_password`), but I'm proposing to create it as a way to solve this problem.

**Comment by behrooz** [comment]
> You mentioned you're using python, right? `subprocess` is part of the standard library (https://docs.python.org/3/library/subprocess.html), and it's the most common way of calling external binaries (external programs). For instance, if you want to call `ls -l` like you would do from the shell, you can do `subprocess.run(["ls", "-l"])` in your python code. This will call from your python code the _external program_ `ls` with the option `-l`.
> 
> Similarly, _if we had a program called `lldap_set_password`_, you could write what I wrote above to call and run it, like you would be able to do from your shell (from the shell you'd write `lldap_set_password --jwt_token abcdef --user tom --password superPa55w0rd --url lldap.my_server.com`).
> 
> This program _doesn't exist yet_ (`lldap_set_password`), but I'm proposing to create it as a way to solve this problem.
So it sould work inside docker container when i call lldap_set_password itself 
but it return
bash: lldap_set_password: command not found
should i run it in specefic directory ?

**Comment by nitnelave** [comment]
As I mentioned just above: _This program doesn't exist yet_, but I'm proposing to create it as a way to solve this problem.

**Comment by nitnelave** [comment]
Let's keep the issue open to track the creation of the tool.
