### ISSUE TITLE
Serve libraries locally

### ISSUE THREAD

**Issue by kaysond** [nitnelave/lldap#93]
Right now all of the below libraries are pointing to cdns. For people like me who run a reverse proxy with some security headers, this can get blocked.

https://github.com/nitnelave/lldap/blob/5b5395103ae56ebbea841be76c000b8b243895dc/app/index.html#L8-L24

Specifically, I set `Content-Security-Policy: default-src 'self' 'unsafe-inline'`, which prevents backend services from loading resources from external sites as a security measure.

Would you be open to a PR that adds these libs to the repo and serves them locally? I'm thinking we should add a `app/static` directory and serve all static files from there (we can also then add a `COPY /app/app/static` to the dockerfile so nothing gets forgotten)

**Comment by nitnelave** [comment]
Hmmm... I'd rather avoid having a copy of the libraries in the repository. However, I'm open to a PR that adds a `main_static.html` and sets up the Dockerfile to copy the main_static and download the files locally. Would that work for you?

**Comment by kaysond** [comment]
I think that's smarter actually. We could add `ARG`s for the versions of the libraries.

What would be in `main_static.html`?

**Comment by nitnelave** [comment]
Same as `main.html`, but referencing the static folder. Basically, if you run the project from source, it'll use the dynamic, CDN libraries, and if you run it from docker it'll use the `static/` folder.

**Comment by JaneJeon** [comment]
What’s stopping you from basically webpack/rollup’ing all of the libraries into the bundle?

**Comment by nitnelave** [comment]
I'd like to avoid making the bundle bigger if possible. That way the logic of the spa can start before the fonts and css are loaded, which should give a faster page load.

Also, I don't know what I'm doing with roll-up :)

**Comment by JaneJeon** [comment]
@nitnelave that's the neat thing about rollup or webpack or any of these "bundlers" (I should know this, javascript is my language of choice) - they don't necessarily have to bundle it all into one big file. In fact, the more common thing to do in production (and I believe it is the _default_ for webpack though I am not sure for rollup) is to chunk them (typically, you'll see a whooooole bunch of tiny little JS files in a folder, and you serve that _folder_, not the singular JS file), so that ONLY the needed parts are loaded when they are requested, so that the MINIMUM amount of JS is even served from the backend in the first place.

You need to try it. @kaysond

**Comment by nitnelave** [comment]
Hmm, after reading both of your links, I see the point of chunk splitting, but I don't think it's useful for our project here:
  - all the code is in one WASM file with no modules and (almost) no js dependencies, and it can't realistically get split up because it's an SPA.
  - the resources that we want to load separately are the css and bootstrap js, which *we know* the user will need, just that the page can get rendered without so we shouldn't block on it. That can easily be achieved by HTML, which is what we're doing here.
  - Since the lazy resources are already split up and potentially cached, I don't see the point of including them in the roll-up: we'd be reimplementing what already exists with simpler tools (HTML).

It sounds like chunk splitting has its place in a dynamic JS project with many dependencies and independent modules, but I don't think it works with the WASM produced by Rust.

**Comment by JaneJeon** [comment]
The idea is you chunk not the _rust_ part, but the _additional libraries_ part. @kaysond

**Comment by nitnelave** [comment]
Yes, but as I said we don't have optional dependencies: we know that the libraries (bootstrap JS and that's it) will be used on the page, so we wouldn't benefit from delaying the request until they're called. It's better to request them from the beginning but not block on them, which is already what we're doing.

**Comment by kaysond** [comment]
> For the questions of control and security concerns, that's the role of the checksums, to make sure that what you downloaded is what you expected. Some libraries already have checksums here, and I'm not opposed to adding checksums to the others. Would you like to do a PR adding them?

I can add hashes for the rest of the libs to my PR. The only reason I didn't before is because the hashes aren't supplied by the devs for the remainder so we'd have to trust the download

**Comment by nitnelave** [comment]
Unless we want to audit all the dependencies ourselves, I'd say that it's fair to assume that there is no hack *of these famous CDNs*, *of these famous libraries*, *right now*. If it turns out there was a hack then the hashes will fail once fixed and/or we'll hear about it. Anyway, given the risk profile of this project, it's an acceptable trade-off.

**Comment by nitnelave** [comment]
Fixed by #96 .
